source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

permalink:     pretty
paginate_path: /page:num

theme: jekyll-theme-cayman