# 자원
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

github_username:  EmrysPage
name: EmrysPage

# 커넥트
permalink:     pretty
paginate: 5
paginate_path: /page:num